# Generated by Django 5.0.3 on 2024-03-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='crateDate',
            new_name='createDate',
        ),
    ]
